[project]
name = "salt"
version = "0.1"
description = "Jet flavour tagging Python package"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
    "pytest==7.2.*",
    "pytest-cov==4.0.*",
    "h5py==3.8.0",
    "numpy==1.24.*",
    "ruamel.yaml==0.17.21",
    "torch==1.13.1",
    "pytorch-lightning[extra]==1.9.0",
    "jsonargparse[signatures]==4.19.0",
    "torchmetrics==0.10.*",
    "comet_ml==3.31.*",
    "tqdm==4.64.*",
    "rich==13.2.0",
    "pre-commit==3.0.*",
    "onnx==1.13.0",
    "onnxruntime==1.13.1",
    "puma-hep",
]

[project.urls]
"Homepage" = "https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt"
"Issue Tracker" = "https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt/-/issues"

[project.scripts]
salt = "salt.main:main"
to_onnx = "salt.to_onnx:main"
get_onnx_metadata = "salt.get_onnx_metadata:main"

[tool.setuptools]
packages = ["salt"]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 99
preview = "True"

[tool.isort]
profile = "black"

[tool.pylint]
format.max-line-length = 99
reports.output-format = "colorized"
messages_control.enable = ["useless-suppression"]

[tool.pytest.ini_options]
log_cli_level = "debug"
filterwarnings = ["ignore::DeprecationWarning"]
