[project]
name = "salt"
version = "0.1"
description = "Jet flavour tagging Python package"
license = {text = "MIT"}
requires-python = ">=3.9"

[project.urls]
"Homepage" = "https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt"
"Issue Tracker" = "https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt/-/issues"

[project.scripts]
salt = "salt.main:main"
to_onnx = "salt.to_onnx:main"
get_onnx_metadata = "salt.utils.get_onnx_metadata:main"

[tool.setuptools]
packages = ["salt"]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 99
preview = "True"

[tool.isort]
profile = "black"

[tool.pylint]
format.max-line-length = 99
reports.output-format = "colorized"
messages_control.enable = ["useless-suppression"]

[tool.pytest.ini_options]
log_cli_level = "debug"
filterwarnings = ["ignore::DeprecationWarning"]
