seed_everything: 42

data:
  train_file: umami_out/preprocessed/PFlow-hybrid-resampled_scaled_shuffled.h5
  val_file: umami_out/preprocessed/PFlow-hybrid-validation-resampled_scaled_shuffled.h5
  scale_dict: umami_out/scale_dict.json
  inputs:
    jet: jets
    track: tracks_loose
  batched_read: True
  batch_size: 1000
  num_workers: 20
  num_jets_train: 22_000_000
  num_jets_val: 1_000_000
  num_jets_test: 1_000_000

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
  log_every_n_steps: 50
  default_root_dir: &default_root_dir logs

  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      save_dir: *default_root_dir
      project_name: salt
      display_summary_level: 0

  callbacks:
    - class_path: salt.callbacks.Checkpoint
    - class_path: salt.callbacks.PredictionWriter
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 20
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2

# configure learning rate
model:
  lrs_config:
    start: 1e-8
    max: 2e-4
    end: 1e-8
