seed_everything: 42

data:
  train_file: <Umami base dir>/preprocessed/PFlow-hybrid-resampled_scaled_shuffled.h5
  val_file: <Umami base dir>/preprocessed/PFlow-hybrid-validation-resampled_scaled_shuffled.h5
  scale_dict: <Umami base dir>/scale_dict.json
  #move_files_temp: null
  inputs:
    jet: jets
    track: tracks
  batched_read: True
  batch_size: 1000
  num_workers: 10
  num_jets_train: 23_000_000
  num_jets_val: 1_000_000
  num_jets_test: 1_000_000

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  #precision: bf16
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
  log_every_n_steps: 50
  default_root_dir: logs

  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      project_name: salt
      display_summary_level: 0

  callbacks:
    - class_path: salt.callbacks.Checkpoint
      init_args:
        monitor_loss: val_jet_classification_loss
    - class_path: salt.callbacks.PredictionWriter
      init_args:
        write_tracks: False
        jet_variables:
          - pt
          - eta
          - HadronConeExclTruthLabelID
          - n_tracks
          - n_truth_promptLepton
        track_variables:
          - truthOriginLabel
          - truthVertexIndex
          - valid
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 20
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2

# configure learning rate
model:
  lrs_config:
    initial: 1e-7
    max: 5e-4
    end: 1e-7
    pct_start: 0.1
