seed_everything: 42

data:
  train_file: /unix/atlastracking/samples/salt_trainings/r22/regression_variable/PFlow-hybrid-resampled_scaled_shuffled.h5
  val_file: /unix/atlastracking/samples/salt_trainings/r22/regression_variable/PFlow-hybrid-resampled_scaled_shuffled.h5
  scale_dict: /unix/atlastracking/samples/salt_trainings/r22/regression_variable/PFlow-scale_dict-22M.json
  inputs:
    jet: jets
    track: tracks_loose
  tasks: &tasks
    jet_classification:
      weight: 1.0
    track_classification:
      weight: 0.5
  batched_read: True
  batch_size: 1000
  num_workers: 20
  num_jets_train: 22_000_000
  num_jets_val: 1_000_000
  num_jets_test: 1_000_000

# TODO: configure learning rate
trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
  log_every_n_steps: 50
  default_root_dir: &default_root_dir logs

  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      save_dir: *default_root_dir
      project_name: salt
      experiment_name: salt

  callbacks:
    - class_path: salt.callbacks.Checkpoint
    - class_path: salt.callbacks.PredictionWriter
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 20
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
