
trainer:
  log_every_n_steps: 50
  callbacks:
    - class_path: salt.callbacks.Checkpoint
    - class_path: salt.callbacks.PredictionWriter
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
