model:
  tasks: &tasks
    jet_classification:
      weight: 1.0
  net:
    class_path: salt.models.JetTagger
    init_args:
      tasks:
        <<: *tasks

      init_net:
        class_path: salt.models.Dense
        init_args:
          input_size: 23
          output_size: &embd_dim 128
          hidden_layers: [128, 128, 128]
          activation: &activation ReLU
          norm_layer: &norm_layer LayerNorm

      gnn: null

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embd_dim

      jet_net:
        class_path: salt.models.Dense
        init_args:
          input_size: *embd_dim
          output_size: 3
          hidden_layers: [128, 64, 32]
          activation: *activation
          norm_layer: *norm_layer
          dropout: 0.1

      track_net: null
