name: dips

model:
  model:
    class_path: salt.models.JetTagger
    init_args:
      init_nets:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.InitNet
              init_args:
                name: track
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: 23
                    output_size: &embed_dim 128
                    hidden_layers: [256]
                    activation: &activation SiLU
                    norm_layer: &norm_layer LayerNorm

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embed_dim

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jet_classification
                input_type: jet
                label: HadronConeExclTruthLabelID
                label_map: { 0: 0, 4: 1, 5: 2 }
                class_names: [ujets, cjets, bjets]
                loss: torch.nn.CrossEntropyLoss
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: *embed_dim
                    output_size: 3
                    hidden_layers: [128, 64, 32]
                    activation: *activation
                    norm_layer: *norm_layer
                    dropout: 0.1

data:
  norm_in_model: True
  variables:
    jet:
      - pt_btagJes
      - eta_btagJes
    track:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - IP3D_signed_d0_significance
      - IP3D_signed_z0_significance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
      - numberOfPixelHoles
      - numberOfSCTHoles
