name: ensemble

model:
  model:
    class_path: salt.models.MLPTagger
    init_args:
      init_nets:
        - name: jet
          dense_config:
            input_size: 2
            hidden_layers: [128, 128, 128]
            output_size: 64
            activation: &activation Mish
            norm_layer: &norm_layer LayerNorm
            dropout: &dropout 0.1

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jet_classification
                input_type: jet
                label: flavour_label
                loss: torch.nn.CrossEntropyLoss
                dense_config:
                  input_size: 64
                  output_size: 3
                  hidden_layers: [128]
                  activation: *activation
                  norm_layer: *norm_layer
                  dropout: *dropout

data:
  norm_in_model: True
  concat_jet_tracks: False
  variables:
    jet:
      - pt_btagJes
      - eta_btagJes
      #- GN120220509_pb
      #- GN120220509_pc
      #- GN120220509_pu
      #- GN1Lep20220509_pb
      #- GN1Lep20220509_pc
      #- GN1Lep20220509_pu
      #- GN2v00_pb
      #- GN2v00_pc
      #- GN2v00_pu
      #- DL1dv01_pu
      #- DL1dv01_pc
      #- DL1dv01_pb

  train_file: /unix/atlastracking/samples/ftag_dumps/truthv2/hlt_ensemble/pp_output_train.h5
  val_file: /unix/atlastracking/samples/ftag_dumps/truthv2/hlt_ensemble/pp_output_val.h5
  norm_dict: /unix/atlastracking/samples/ftag_dumps/truthv2/hlt_ensemble/norm_dict.yaml
  class_dict: /unix/atlastracking/samples/ftag_dumps/truthv2/hlt_ensemble/class_dict.yaml
  input_names:
    jet: jets
  batch_size: 2000
  num_workers: 15
  num_jets_train: -1
  num_jets_val: -1
  num_jets_test: -1

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: [1]
  precision: 16-mixed
