name: flow

data:
  train_file: /share/rcifdata/svanstroud/data/flow/preprocessed/PFlow-hybrid-resampled_scaled_shuffled.h5
  val_file: /share/rcifdata/svanstroud/data/flow/preprocessed/PFlow-hybrid-validation-resampled_scaled_shuffled.h5
  scale_dict: /share/rcifdata/svanstroud/data/flow/scale_dict.json
  move_files_temp: /dev/shm/svanstro/salt/
  inputs:
    jet: jets
    track: tracks
    flow: flow

model:
  model:
    class_path: salt.models.JetTagger
    init_args:

      init_nets:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.InitNet
              init_args:
                name: track
                net:
                  class_path: salt.models.Dense
                  init_args: &init
                    input_size: 23
                    output_size: &embed_dim 128
                    hidden_layers: [256]
                    activation: &activation SiLU
                    norm_layer: &norm_layer LayerNorm

            - class_path: salt.models.InitNet
              init_args:
                name: flow
                net:
                  class_path: salt.models.Dense
                  init_args:
                    <<: *init
                    input_size: 6

      gnn:
        class_path: salt.models.Transformer
        init_args:
          attention: salt.models.ScaledDotProductAttention
          embed_dim: *embed_dim
          out_proj: False
          num_heads: 8
          num_layers: 6
          residual: true
          norm_layer: *norm_layer
          activation: *activation
          dropout: &dropout 0.1

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embed_dim

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jet_classification
                label: jets/labels
                loss: torch.nn.CrossEntropyLoss
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: *embed_dim
                    output_size: 3
                    hidden_layers: [128, 64, 32]
                    activation: *activation
                    norm_layer: *norm_layer
                    dropout: *dropout
