model:
    model:
      class_path: salt.models.JetTagger
      init_args:

        gnn:
          class_path: salt.models.TransformerEncoder
          init_args:
            mha_config:
              num_heads: 8
              attention:
                class_path: salt.models.GATv2Attention
                init_args:
                  num_heads: 8
                  head_dim: 16
