name: GN1Xbb

data:
  train_file: /eos/user/u/umami/training-samples/gnn/xbb/Xbb-hybrid-resampled_scaled_shuffled.h5
  val_file: /eos/user/u/umami/training-samples/gnn/xbb/Xbb-hybrid-validation-resampled_scaled_shuffled.h5
  scale_dict: /eos/user/u/umami/training-samples/gnn/xbb/Xbb-scale_dict.json
  inputs:
    jet: jets
    track: tracks
  num_jets_train: -1
  num_jets_val: -1
  num_jets_test: -1
  batch_size: 1000
  num_workers: 20

trainer:
  max_epochs: 100
  devices: 1
  callbacks:
    - class_path: salt.callbacks.Checkpoint
      init_args:
        monitor_loss: val_jet_classification_loss
    - class_path: salt.callbacks.PredictionWriter
      init_args:
        jet_variables:
          - pt
          - eta
          - mass
          - R10TruthLabel_R22v1
          - R10TruthLabel_R22v1_TruthJetMass
          - R10TruthLabel_R22v1_TruthJetPt
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 20
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2

model:
  model:
    class_path: salt.models.JetTagger
    init_args:
      init_nets:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.InitNet
              init_args:
                name: track
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: 23
                    output_size: &embed_dim 128
                    hidden_layers: [128]
                    activation: &activation SiLU
                    norm_layer: &norm_layer LayerNorm

      gnn:
        class_path: salt.models.TransformerEncoder
        init_args:
          embed_dim: *embed_dim
          num_layers: 2
          out_dim: &out_dim 128
          mha_config:
            num_heads: 4
            attention:
              class_path: salt.models.ScaledDotProductAttention
            out_proj: False
          dense_config:
            norm_layer: *norm_layer
            activation: *activation
            hidden_layers: [128]
            dropout: &dropout 0.1

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *out_dim

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.ClassificationTask
              init_args:
                name: jet_classification
                label: jets/labels
                loss: torch.nn.CrossEntropyLoss
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: *out_dim
                    output_size: 4
                    hidden_layers: [64, 32]
                    activation: *activation
                    norm_layer: *norm_layer
                    dropout: *dropout

            - class_path: salt.models.ClassificationTask
              init_args:
                name: track_classification
                label: tracks/labels/truthOriginLabel
                weight: 0.5
                loss:
                  class_path: torch.nn.CrossEntropyLoss
                  init_args:
                    weight:
                      [7.62, 104.91, 1.56, 20.65, 14.05, 14.06, 1.0, 36.07]
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: 128
                    context_size: 128
                    output_size: 8
                    hidden_layers: [64, 32]
                    activation: *activation
                    norm_layer: *norm_layer
                    dropout: *dropout

            - class_path: salt.models.VertexingTask
              init_args:
                name: tracks/labels/track_vertexing
                label: truthVertexIndex
                weight: 1.5
                loss:
                  class_path: torch.nn.BCEWithLogitsLoss
                  init_args:
                    reduction: none
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: 256
                    context_size: *out_dim
                    hidden_layers: [64, 32]
                    output_size: 1
                    activation: *activation
