seed_everything: 42

model:
  loss_weights:
    flavour: 1.0
  net:
    class_path: salt.models.tagger.JetTagger
    init_args:
      init_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 21
          output_size: 128
          hidden_layers:
          - 128
          activation: relu
          norm_layer: layernorm
      gnn:
        class_path: salt.models.transformer.Transformer
        init_args:
          embd_dim: 128
          num_heads: 4
          num_layers: 6
          residual: True
          norm_layer: layernorm
          dropout: 0.1
          activation: relu
      pool_net:
        class_path: salt.models.pooling.GlobalAttentionPooling
        init_args:
          input_size: 128
      jet_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 128
          output_size: 3
          hidden_layers:
          - 128
          activation: relu
          norm_layer: layernorm
          dropout: 0.1

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4

data:
  filename: /unix/atlastracking/samples/gnn_training/note/dips/preprocessed/PFlow-hybrid-resampled_scaled_shuffled.h5
  batch_size: 1000
  num_workers: 10
  num_jets_train: 5_000_000
  num_jets_val: 100_000
  num_jets_test: 100_000
  jet_class_dict: &jet_class_dict
      0:
        label: 0
        weight: 1.0
      4:
        label: 1
        weight: 1.0
      5:
        label: 2
        weight: 1.0


trainer:
  precision: 32
  max_epochs: 10
  accelerator: gpu
