name: regression_example

model:
  model:
    class_path: salt.models.JetTagger
    init_args:
      init_nets:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.InitNet
              init_args:
                name: track
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: 21
                    output_size: &embed_dim 128
                    hidden_layers: [256]
                    activation: &activation SiLU
                    norm_layer: &norm_layer LayerNorm

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embed_dim

      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
            - class_path: salt.models.RegressionTask
              init_args:
                name: regression_with_mean_std_norm
                input_type: jet
                targets: HadronConeExclTruthLabelLxy
                target_denominators: pt_btagJes
                weight: 20
                loss:
                  class_path: torch.nn.MSELoss
                  init_args:
                    reduction: none
                net:
                  class_path: salt.models.Dense
                  init_args:
                    input_size: *embed_dim
                    output_size: 1
                    hidden_layers: [128, 64, 32]
                    activation: *activation

            # - class_path: salt.models.RegressionTask
            #   init_args:
            #     name: regression_with_ratio_norm
            #     input_type: jet
            #     label: HadronConeExclTruthLabelLxy
            #     label_denominator: pt_btagJes
            #     loss:
            #       class_path: torch.nn.MSELoss
            #       init_args:
            #         reduction: none
            #     net:
            #       class_path: salt.models.Dense
            #       init_args:
            #         input_size: *embed_dim
            #         output_size: 1
            #         hidden_layers: [128, 64, 32]
            #         activation: *activation

data:
  variables:
    jet:
      - pt_btagJes
      - eta_btagJes
    track:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - IP3D_signed_d0_significance
      - IP3D_signed_z0_significance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
