name: dips

model:
  model:
    class_path: salt.models.JetTagger
    init_args:

      init_net:
        class_path: salt.models.Dense
        init_args:
          input_size: 23
          output_size: &embd_dim 128
          hidden_layers: [128, 128, 128]
          activation: &activation ReLU
          norm_layer: &norm_layer LayerNorm

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embd_dim

      jet_net:
        class_path: salt.models.RegressionTask
        init_args:
          name: jet_classification
          loss: torch.nn.GaussianNLLLoss
          net:
            class_path: salt.models.Dense
            init_args:
              input_size: *embd_dim
              output_size: 2
              hidden_layers: [128, 64, 32]
              activation: *activation
              norm_layer: *norm_layer
              dropout: 0.1
