model:
  model:
    class_path: salt.models.SaltModel
    init_args:
      encoder:
        class_path: salt.models.TransformerV2
        init_args:
          dim: 256
          num_layers: 4
          num_heads: 8
          out_dim: 128
          gated: true
