build_docker:
  stage: builds
  needs: []
  variables:
    TO: $CI_REGISTRY_IMAGE:latest
    GIT_SSL_NO_VERIFY: "true"
    DOCKER_FILE: setup/Dockerfile
  tags:
    - docker-image-build
  script:
    - ignore
