pages:
  image: python:3.9.14
  stage: docs
  needs: []
  script:
    - pip install mkdocs==1.4.1 mkdocs-material==8.5.7 mkdocs-markdownextradata-plugin>=0.2.5
    - mkdocs build -d public
    - if [[ -f _redirects ]]; then cp _redirects public; fi;
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  #rules:
  #  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH=="atlas-flavor-tagging-tools/algorithms/salt"
  #    when: always
