pytest:
  stage: tests
  needs: ["build_docker"]
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - cd salt
    - coverage run --source salt -m pytest --show-capture=stdout
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
