variables:
  TEST_CMD: coverage run -p --source salt -m pytest --show-capture=stdout

.job-template: &job-template
  stage: tests
  needs: [build_docker_test]
  image: "$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test"
  artifacts:
    paths: [.coverage*]

test-models:
  <<: *job-template
  script:
    - $TEST_CMD salt/tests/test_models.py

test-pipelines-misc:
  <<: *job-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::TestTrainMisc

test-pipelines-models:
  <<: *job-template
  script:
    - $TEST_CMD salt/tests/test_pipeline.py::TestModels

test-union-find:
  <<: *job-template
  script:
    - $TEST_CMD salt/tests/test_union_find.py
